/*tabla de auditoria de eventos , verifica los eventos que se provocan en la tabla clientes , como actualizar o eliminar , y nos da informacion del valor antiguo que fue cambioo en este caso usamos la columna nombre, los eventos se puede
ver que usuario , nombre de maquina y mas , desde donde hace conexion el cliente.*/
CREATE TABLE auditoria_eventos (
    id_evento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_evento VARCHAR2(20),
    usuario_bd VARCHAR2(50),
    fecha_evento TIMESTAMP,
    usuario_so VARCHAR2(50),
    ip VARCHAR2(50),
    nombre_maquina VARCHAR2(100),
    valores_antiguos CLOB

);

CREATE OR REPLACE TRIGGER trg_auditoria_eventos
AFTER DELETE OR UPDATE ON clientes 
FOR EACH ROW
DECLARE
    tipo_evento VARCHAR2(20);
BEGIN
    IF DELETING THEN
        tipo_evento := 'DELETE';
    ELSE
        tipo_evento := 'UPDATE';
    END IF;

    INSERT INTO auditoria_eventos (tipo_evento, usuario_bd, fecha_evento, usuario_so, ip, nombre_maquina, valores_antiguos)
    VALUES (tipo_evento, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSTIMESTAMP, SYS_CONTEXT('USERENV', 'OS_USER'), SYS_CONTEXT('USERENV', 'IP_ADDRESS'), SYS_CONTEXT('USERENV', 'HOST'),:OLD.ID_CLIENTE);
END;

INSERT INTO clientes (id_cliente, nombre, apellido, correo, telefono, direccion, password)
VALUES (4, 'Sandra', 'Martinez', 'sandra@example.com', '123456789','100mts norte de los colos', '123456');


INSERT INTO clientes (id_cliente, nombre, apellido, correo, telefono, direccion, password)
VALUES (5, 'Aldemar', 'Ulate', 'aldemarU@gmail.com', '89569711','75mts norte de pizza hut, heredia', '1234');

select * from clientes
order by id_cliente asc ;

select * from auditoria_eventos;

UPDATE clientes
SET password = 'popeye'
WHERE id_cliente = 5;

DELETE FROM clientes
WHERE id_cliente = 4;